name: speedtest

# 触发条件
on:
  workflow_dispatch:

  schedule:
    - cron: '0 */4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: "3.11"
        cache: "pip"
        
    - name: Set Timezone
      run: sudo timedatectl set-timezone 'Asia/Tehran'
     
    - name: Run Lite Speedtest
      run: |
        git clone https://github.com/bestofthebestbabe/dare
        cd dare
        sudo sh ./utils/speedtest/speedtest.sh
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .
        git clean -f -d
        git commit -m "done!"
        git push origin main
        ls
        
    - name: Push Change
      uses: ad-m/github-push-action@master
      with:
        branch: main
