name: speedtest

# 触发条件
on:
  workflow_dispatch:

  schedule:
    - cron: '0 */4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Load Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set Timezone
      run: sudo timedatectl set-timezone 'Asia/Tehran'

    - name: Run Lite Speedtest
      run: |
        sudo sh ./utils/speedtest/speedtest.sh
